[package]
name = "substrate-client-keystore"
version = "0.6.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2021"

[dependencies]
parking_lot = "0.12.0"
async-trait = "0.1.52"
hex = "0.4.3"
serde_json = "1.0.79"

# Substrate dependencies
sp-core = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-keystore = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sc-keystore = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-keyring = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-application-crypto = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }

[dev-dependencies]
tempfile = "3.3.0"
