[package]
name = "ac-node-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ['derive'], default-features = false }
derive_more = { version = "0.99.17" }
#TODO get from parity when our changes are accepted
frame-metadata = { version = "15.0.0", default-features = false, git = "https://github.com/integritee-network/frame-metadata", features = ["v14", "full_derive"] }
#frame-metadata = { version = "15.0.0", features = ["v14"], default-features = false }
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "2.0.1", features = ["derive", "decode"] , default-features = false }
serde = { version = "1.0.136", features = ["derive"], default-features = false }
serde_json = { version = "1.0.79", default-features = false, features = ["alloc"] }

# local deps
ac-primitives = { path = "../primitives", default-features = false }

# substrate deps
frame-support = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
frame-system = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-std = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-runtime = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }

# need to add this for `no_std`
sp-application-crypto = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0", features = ["full_crypto"] }
sp-runtime-interface = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }

[features]
default = ["std"]
# To support `no_std` builds in non-32 bit environments.
disable_target_static_assertions = [
    "sp-runtime-interface/disable_target_static_assertions"
]
std = [
    "codec/std",
    "frame-metadata/std",
    "hex/std",
    "log/std",
    "scale-info/std",
    "serde/std",
    "serde_json/std",
    # local deps
    "ac-primitives/std",
    # substrate-deps
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    # no_std support
    "sp-application-crypto/std",
    "sp-runtime-interface/std",
]
