[package]
name = "substrate-api-client"
version = "0.6.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2021"

[workspace]
members = [
	".",
	"compose-macros",
	"client-keystore",
	"node-api",
	"test-no-std",
	"tutorials/api-client-tutorial",
]

[dependencies]
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
log = { version = "0.4.14", optional = true }
#TODO get from parity when our changes are accepted
metadata = { version = "15.0.0", default-features = false, git = "https://github.com/integritee-network/frame-metadata", package = "frame-metadata", features = ["v14", "full_derive"] }
#metadata = { version = "15.0.0", default-features = false, package = "frame-metadata", features = ["v14"] }
primitive-types = { version = "0.11.1", optional = true, features = ["codec"] }
serde = { version = "1.0.136", optional = true, features = ["derive"] }
serde_json = { version = "1.0.79", optional = true }
thiserror = { version = "1.0.30", optional = true }
ws = { version = "0.9.2", optional = true, features = ["ssl"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ['derive'] }

# Substrate dependencies
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-version = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0", package = "sp-version" }
balances = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0", package = "pallet-balances" }
staking = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0", package = "pallet-staking" }
system = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0", package = "frame-system" }
transaction-payment = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0", package = "pallet-transaction-payment" }
sp-rpc = { optional = true, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-runtime = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
support = { default-features = false, git = "https://github.com/tearust/substrate.git", package = "frame-support", branch = "v4.0" }
sp-std = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
# need to add this for the app_crypto macro
sp-application-crypto = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0", features = ["full_crypto"] }

sp-runtime-interface = { default-features = false, git = "https://github.com/tearust/substrate.git", branch = "v4.0" }

# local deps
ac-compose-macros = { path = "compose-macros", default-features = false }
ac-node-api = { path = "node-api", default-features = false }
ac-primitives = { path = "primitives", default-features = false }

[dev-dependencies]
env_logger = "0.9.0"
node-template-runtime = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
sp-keyring = { git = "https://github.com/tearust/substrate.git", branch = "v4.0" }
clap = { version = "2.33", features = ["yaml"] }
wabt = "0.10.0"


[features]
default = ["std", "ws-client"]
# To support `no_std` builds in non-32 bit environments.
disable_target_static_assertions = [
 "sp-runtime-interface/disable_target_static_assertions"
]
std = [
	"sp-application-crypto/std",
	"sp-core/std",
	"codec/std",
	"metadata/std",
	"sp-version",
	"balances",
	"system",
	"sp-runtime/std",
	"support/std",
	"sp-std/std",
	"serde/std",
	"serde_json",
	"log",
	"hex/std",
	"primitive-types",
	"thiserror",
	"sp-rpc",
	"sp-runtime-interface/std",
	"transaction-payment/std",
	# local deps
	"ac-compose-macros/std",
	"ac-node-api/std",
	"ac-primitives/std",
]
ws-client = ["ws"]
staking-xt = ["std", "staking"]

